# Generated by Django 3.1 on 2024-10-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productgallery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'variation_category', 'variation_value')},
        ),
    ]
